babel_battle_platform/babel_battle_platform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('battle_platform.urls', namespace='battle')),
]

babel_battle_platform/battle_platform/urls.py
# coding:utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^script_upload/$', views.script_upload, name='script_upload'),
    url(r'^download/([A-Za-z0-9_.\/\-]+)/$', views.download, name='download'),
    url(r'^play/([0-9_.]+)/$', views.video_play, name='video_play'),
]

babel_battle_platform/battle_platform/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

game_choices = ((0, 'Royal war'), (1, 'None'))


def file_path_script(instance, _):
    tt = str(instance.upload_time)
    return '%s.lua' % (tt.split('.')[0])


class UploadRecord(models.Model):
    upload_user = models.ForeignKey(User)
    upload_time = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    upload_game = models.IntegerField(choices=game_choices, default=0)
    upload_script = models.FileField(upload_to=file_path_script, blank=True)

babel_battle_platform/battle_platform/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from .models import UploadRecord


class UploadRecordForm(ModelForm):
    class Meta:
        model = UploadRecord
        fields = ('upload_game', 'upload_script')
        widgets = {
            'upload_game': forms.RadioSelect(),
            'upload_script': forms.FileInput(attrs={'class': 'file_input'}),
        }

babel_battle_platform/battle_platform/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import subprocess
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import UploadRecordForm
from .models import UploadRecord
from django.conf import settings

from django.template.defaulttags import register


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


def homepage(request):
    if request.user.is_authenticated():
        upload_records = UploadRecord.objects.filter(upload_user=request.user)
        game_choices = {0: 'Royal war', 1: None}
        return render(request, 'homepage.html', {'username': request.user.username.split('@')[0],
                                                 'records': upload_records, 'choices': game_choices, })
    else:
        return render(request, 'homepage.html')


def login(request):
    information = {'option': 'login'}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        information['username'] = username
        information['password'] = password
        if username == '':
            information['error'] = 'Email is required!'
        elif password == '':
            information['error'] = 'Password is required!'
        else:
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('battle:homepage'))
            else:
                information['error'] = 'Your email or password is wrong!'
    return render(request, 'login_register.html', information)


@login_required(login_url='/login/')
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('battle:homepage'))


def register(request):
    information = {'option': 'register'}
    if request.method == 'POST':
        username = request.POST['r_username']
        password1 = request.POST['r_password1']
        password2 = request.POST['r_password2']
        information['r_username'] = username
        information['r_password1'] = password1
        information['r_password2'] = password2
        if username == '':
            information['r_error'] = 'Email is required!'
        elif password1 == '' or password2 == '':
            information['r_error'] = 'Password is required!'
        elif password1 != password2:
            information['r_error'] = 'Your passwords are not consistent!'
        else:
            if User.objects.filter(username=username).count() != 0:
                information['r_error'] = 'The email is already registered, please login!'
            else:
                user = User.objects.create_user(username=username, password=password1)
                user.save()
                auth.authenticate(username=username, password=password1)
                auth.login(request, user)
                return HttpResponseRedirect(reverse('battle:homepage'))
    return render(request, 'login_register.html', information)


def run_script(file_id):
    script = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'check.py')
    subprocess.Popen(["python", script, file_id])


@login_required(login_url='/login/')
def script_upload(request):
    if request.method == 'POST':
        form = UploadRecordForm(request.POST, request.FILES)
        if form.is_valid():
            model = form.save(commit=False)
            script = model.upload_script
            script_split = str(script).split('.')
            if len(script_split) == 0 or script_split[-1] != 'lua':
                error = 'File format error!'
                return render(request, 'script_upload.html', {'form': form, 'error': error})
            else:
                model.upload_user = request.user
                model.save()
                origin_name = os.path.join(settings.MEDIA_ROOT, str(model.upload_time).split('.')[0].replace(' ', '_').replace(':', '')+ '.lua')
                new_name = os.path.join(settings.MEDIA_ROOT, str(model.id) + '.lua')
                os.rename(origin_name, new_name)
                model.upload_script.name = str(model.id) + '.lua'
                model.save()
                run_script(str(model.id))
                return HttpResponseRedirect(reverse('battle:homepage'))
    else:
        form = UploadRecordForm()
    return render(request, 'script_upload.html', {'form': form, })


@login_required(login_url='/login/')
def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/force-download")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    else:
        raise Http404


@login_required(login_url='/login/')
def video_play(request, video_id):
    static_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'static')
    new_name = os.path.join(static_dir, 'video', video_id + '.mp4')
    if os.path.exists(new_name):
        return render(request, 'video_play.html', {'video_id': video_id})
    else:
        return HttpResponseRedirect(reverse('battle:homepage'))

babel_battle_platform/battle_platform/templates/homepage.html
<html>

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>对战平台</title>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-confirmation.min.js' %}"></script>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'battle:homepage' %}"><span>对战平台</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>{{ username }}</a></li>
                {% else %}
                    <li><a href="{% url 'battle:login' %}">登录</a></li>
                {% endif %}
                <li><a href="{% url 'battle:register' %}">注册</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'battle:logout' %}">退出</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>


<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <button class="btn btn-primary pull-right popover-toggle" style="margin-left: 10px"
                        onclick="{location.href={% url 'battle:script_upload' %}}">
                    <span class="glyphicon glyphicon-plus" ></span> 上传新脚本
                </button>

                <p style="font-size: 25px"> 对战记录 </p>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <td class="active">时间</td>
                        <td class="active">所选游戏</td>
                        <td class="active">上传脚本</td>
                        <td class="active">视频回放</td>
                    </tr>


                    </thead>
                    <tbody>
                    {% for record in records %}
                        <tr>
                            <th>{{ record.upload_time }}</th>
                            <th>{{ choices|get_item:record.upload_game }}</th>
                            <th><a href="{% url 'battle:download' record.upload_script %}">{{ record.upload_script }}</a></th>
                            <th><a href="{% url 'battle:video_play' record.id %}">回放</a></th>
                        </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

</body>
</html>

babel_battle_platform/battle_platform/templates/login_register.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'login_style.css' %}">
</head>

<body>

<div class="pen-title">
    <h1>Deep Comments</h1>
</div>
<!-- Form Module-->
<div class="module form-module">
    <div class="toggle"><i class="fa fa-times {% if option == 'login' %}fa-pencil{% endif %}"></i></div>
    <div class="form" {% if option == 'login' %}style="display: block"{% else %}style="display: none"{% endif %}>
        <h2>Login to your account</h2>
        <form method="post" action="{% if next %}{% url 'battle:login' %}?next={{ next }}{% else %}{% url 'battle:login' %}{% endif %}">
            {% csrf_token %}
            <input name="username" type="email" placeholder="Email" value="{{ username }}"/>
            <input name="password" type="password" placeholder="Password" value="{{ password }}"/>
            <button type="submit">Login</button>
            <p style="color:#F00">{{ error }}</p>
        </form>
    </div>

    <div class="form" {% if option == 'register' %}style="display: block"{% else %}style="display: none"{% endif %}>
        <h2>Create an account</h2>
        <form method="post" action="{% url 'battle:register' %}">
            {% csrf_token %}
            <input name="r_username" type="email" placeholder="Email" value="{{ r_username }}"/>
            <input name="r_password1" type="password" placeholder="Password" value="{{ r_password1 }}"/>
            <input name="r_password2" type="password" placeholder="Password" value="{{ r_password2 }}"/>
            <button type="submit">Register</button>
            <p style="color:#F00">{{ r_error }}</p>
        </form>
    </div>
    <div class="cta"><a href="">Forgot your password?</a></div>
</div>

<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
{#<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>#}

<script type="text/javascript">
    $(function () {
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    });
</script>

</body>
</html>

babel_battle_platform/battle_platform/templates/script_upload.html
<!DOCTYPE html>
<html>

{% load staticfiles %}

<head>
    <meta charset="utf-8"/>
    <title>脚本上传</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'student_form/formoid-solid-green.css' %}" type="text/css"/>
    <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-confirmation.min.js' %}"></script>
</head>

<body class="blurBg-false" style="background-color:#EBEBEB">

<div class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'battle:homepage' %}"><span>对战平台</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                {% else %}
                    <li><a href="{% url 'battle:login' %}">登录</a></li>
                {% endif %}
                <li><a href="{% url 'battle:register' %}">注册</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'battle:logout' %}">退出</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<form id="student-form" enctype="multipart/form-data" class="formoid-solid-green"
      action="{% url 'battle:script_upload' %}"
      style="background-color:#FFFFFF;font-size:17px;font-family:'Roboto',Arial,Helvetica,sans-serif;color:#34495E;max-width:960px;min-width:150px"
      method="post">
    {% csrf_token %}
    <div class="title"><h2>填写您的对战脚本信息</h2></div>

    <br>
    <div class="element-radio">
        <label class="title" style="font-size: 20px">您选择的游戏是？</label>
        {% for b in form.upload_game %}
            <div class="column column3">
                <label for="{{ b.id_for_upload_game }}">
                    {{ b.tag }}
                    <span>{{ b.choice_label }}</span>
                </label>
            </div>
            <span class="clearfix"></span>
        {% endfor %}
    </div>

    <div class="element-separator">
        <hr>
        <h3 class="section-break-title"></h3>
    </div>

    <br>

    <div class="element-file">
        <label class="title" style="font-size: 20px; padding-bottom: 5px">请上传脚本</label>
        <div class="item-cont"><label class="large">
            <div class="button">选择文件</div>
            {{ form.upload_script }}
            <div class="file_text">Scan and Upload your Battle Script</div>
            <span class="icon-place"></span></label></div>
    </div>
                <p style="color:#F00">{{ error }}</p>


    <div id="submit_div" class="submit">
        <input id="next" type="submit" value="提交">
    </div>
</form>

<script type="text/javascript" src="{% static 'student_form/formoid-solid-green.js' %}"></script>

</body>
</html>

babel_battle_platform/battle_platform/templates/video_play.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>视频播放</title>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-confirmation.min.js' %}"></script>
</head>

<body>

<div class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'battle:homepage' %}"><span>对战平台</span></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                {% else %}
                    <li><a href="{% url 'battle:login' %}">登录</a></li>
                {% endif %}
                <li><a href="{% url 'battle:register' %}">注册</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'battle:logout' %}">退出</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
    <div align="center" style="margin-top:40px;">
        <video controls>
            <source src='/static/video/{{ video_id }}.mp4' type="video/mp4">
        </video>
    </div>

</body>
</html>